project_id = "zxcqqsviwtwxukizibef"

[functions.fetch-free-games]
verify_jwt = true

[functions.enrich-game-description]
verify_jwt = true

[functions.fetch-game-patches]
verify_jwt = true

[functions.rewrite-game-patches]
verify_jwt = true

[functions.backfill-game-descriptions]
verify_jwt = true
